
services:
  app:
    container_name: laravel_app
    build:
      context: ./Authentification
      dockerfile: Dockerfile
    ports:
      - "8080:80" 
    volumes:
      - ./Authentification:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: cloud
      DB_USERNAME: postgres
      DB_PASSWORD: secret
    depends_on:
      - db 
    command: >
      bash -c "php artisan key:generate --force && php artisan migrate --force && php artisan db:seed --force && apache2-foreground"


  db:
    image: postgres:16
    container_name: laravel_db
    environment:
      POSTGRES_DB: cloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  

volumes:
  pgdata:  
