spring.application.name=crypto

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# Configuration de la base de donn�es
spring.datasource.url=jdbc:postgresql://localhost:5433/cloud
spring.datasource.username=postgres
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=none

# Configuration de l'API Laravel
laravel.api.url=http://project-cloud-laravel_app

management.endpoints.web.exposure.include=*
