spring.application.name=crypto

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# Configuration de la base de données
spring.datasource.url=jdbc:postgresql://localhost:5432/springsolo
spring.datasource.username=postgres
spring.datasource.password=system
spring.jpa.hibernate.ddl-auto=none

# Configuration de l'API Laravel
laravel.api.url=http://localhost:8000
